package com.pluralsight.streaming;

import org.apache.flink.api.common.ExecutionConfig;
import org.apache.flink.api.common.functions.FilterFunction;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;

public class HighSpeedDetection {

    public static void main(String[] args) throws Exception {

        final StreamExecutionEnvironment env =
                StreamExecutionEnvironment.getExecutionEnvironment();

        ExecutionConfig executionConfig = env.getConfig();

        System.out.println("***Autogenerated UIDs : " +
                executionConfig.hasAutoGeneratedUIDsEnabled());
        System.out.println("***Parallelism : " +
                executionConfig.getParallelism());
        System.out.println("***Max Parallelism : " +
                executionConfig.getMaxParallelism());
        System.out.println("***Execution Mode : " +
                executionConfig.getExecutionMode());
        System.out.println("***Restart Strategy : " +
                executionConfig.getRestartStrategy());
        
        env.getConfig().disableAutoGeneratedUIDs();

        DataStream<String> dataStream = env
                .socketTextStream("localhost", 9000).uid("car-speed-read")
                .filter(new Filter())
                .name("High-speed Filter Operaton").uid("car-speed-filter");

        dataStream.print().uid("car-speed-print");

        env.execute("Car speed detection");
    }

    public static class Filter implements FilterFunction<String> {

        public boolean filter(String input) throws Exception {
            try {
                String[] tokens = input.split(",");

                if (tokens.length == 2 && Float.parseFloat(tokens[1].trim()) > 65) {
                    return true;
                }
            } catch (Exception ex) {
            }

            return false;
        }


    }

}
